### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by cabanel-1847** [hsdn/Boss-Helper#1]
tera crash when i type mm scan and teleport there , is it because of my connection?

**Comment by justkeepquiet** [comment]
Hi. In some cases, the Tera may crash while scanning. Try disabling the instant teleport function (command **bh teleport**).

You can use the scan function without instant teleport. Start the scanning process.
After finding the NPC, press the "Apex Urgency" skill (or similar) to move to the NPC.

If the Tera still crashes after doing this, avoid using the scan function.

**Comment by cabanel-1847** [comment]
hi thanks for the reply , it still crashed once a boss its found after scan
