### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tiketdata-andre** [hsdn/Boss-Helper#6]
![image](https://github.com/hsdn/Boss-Helper/assets/52944290/9830b5d0-be10-404e-9421-8fc24bdef2e1)

I got this error asking for "notifier", is it a separate module?

**Comment by justkeepquiet** [comment]
You need to use a Toolbox with automatic updates feature: https://github.com/tera-private-toolbox/tera-toolbox

For manual installation you will need a dependency: https://github.com/SerenTera/tera-notifier
